### ISSUE TITLE
`ldconfig -p` not found

### ISSUE THREAD

**Issue by vchuravy** [climate-machine/slurmci#14]
It looks like the recent set of failures is due to `/usr/sbin` missing from the `$PATH`. https://gist.github.com/climabot/be9d8b0da3a0881b5763b7c3e4f8cb6c#file-out_8964796-L34

https://gist.github.com/climabot/be9d8b0da3a0881b5763b7c3e4f8cb6c#file-out_8964796-L281
`which ldconfig => /usr/sbin/ldconfig`.

Citing from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=617898

```
The simple solution to the original person's problem is to add this to
his /etc/cron.d/logrotate script:

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

However, I was a little surprised to find that the default $PATH is
different for scripts run from /etc/cron.d and /etc/cron.daily. Although
it's unlikely, a misunderstanding about that could perhaps cause someone
to make a security-related mistake.
```

**Comment by kpamnany** [comment]
This was fixed by #15.
