### ISSUE TITLE
Don't miss commits

### ISSUE THREAD

**Issue by kpamnany** [climate-machine/slurmci#4]
Run tests for _all_ commits since the last on which tests were run, rather than only the most recent commit.

**Comment by simonbyrne** [comment]
I don't know if this is really necessary. bors will handle bijection itself if there is a failure.

**Comment by kpamnany** [comment]
Well, the performance part needs to run on every commit made in the day since it last ran, to get good tracking of performance. And the logic is shared, so tests can do it too.

**Comment by simonbyrne** [comment]
Does it? My idea was that we could just run it periodically to ensure we don't get performance regressions.

If we did want to do this, we would have to make sure everyone squashes their commits (since otherwise we may have intermediate commits which are broken.

**Comment by kpamnany** [comment]
Good point!

Go ahead and close this if you decide not to do that.
